### ISSUE TITLE
Scheduled and previous events page - same aesthetics as DLI events page?

### ISSUE THREAD

**Issue by willfurnass** [rsessitedev/rsessitedev.github.io#4]
i.e. https://rsessitedev.github.io/training/events/

Can we make this look (and function, in terms of updates) like the events listing on the DLI page?

**Comment by twinkarma** [comment]
@willfurnass Yes I'm planning to make them all separate events so that it can be laid out the same as the rest of the site.

**Comment by twinkarma** [comment]
@willfurnass Done, see 92db573469517b7d905f84ece68e170c3ff7a92b. People now need to add more info to events.
